// DispIDs.h: Defines a DISPID for each COM property and method we're providing.

// IProgressBar
// properties
#define DISPID_PROGBAR_ACTIVATEMARQUEE							1
#define DISPID_PROGBAR_APPEARANCE										2
#define DISPID_PROGBAR_BACKCOLOR										3
#define DISPID_PROGBAR_BARCOLOR											4
#define DISPID_PROGBAR_BARSTYLE											5
#define DISPID_PROGBAR_BORDERSTYLE									6
#define DISPID_PROGBAR_CURRENTVALUE									DISPID_VALUE
#define DISPID_PROGBAR_DISABLEDEVENTS								7
#define DISPID_PROGBAR_DONTREDRAW										8
#define DISPID_PROGBAR_ENABLED											DISPID_ENABLED
#define DISPID_PROGBAR_HOVERTIME										9
#define DISPID_PROGBAR_HWND													10
#define DISPID_PROGBAR_MARQUEESTEPDURATION					11
#define DISPID_PROGBAR_MAXIMUM											12
#define DISPID_PROGBAR_MINIMUM											13
#define DISPID_PROGBAR_MOUSEICON										14
#define DISPID_PROGBAR_MOUSEPOINTER									15
#define DISPID_PROGBAR_ORIENTATION									16
#define DISPID_PROGBAR_PROGRESSSTATE								17
#define DISPID_PROGBAR_REGISTERFOROLEDRAGDROP				18
#define DISPID_PROGBAR_RIGHTTOLEFTLAYOUT						19
#define DISPID_PROGBAR_SMOOTHREVERSE								20
#define DISPID_PROGBAR_STEPWIDTH										21
#define DISPID_PROGBAR_SUPPORTOLEDRAGIMAGES					22
#define DISPID_PROGBAR_VERSION											23
#define DISPID_PROGBAR_DETECTDOUBLECLICKS						27
#define DISPID_PROGBAR_DISPLAYTEXT									28
#define DISPID_PROGBAR_FONT													29
#define DISPID_PROGBAR_FORECOLOR										30
#define DISPID_PROGBAR_HALIGNMENT										31
#define DISPID_PROGBAR_RIGHTTOLEFT									32
#define DISPID_PROGBAR_TEXT													33
#define DISPID_PROGBAR_TEXTSHADOWCOLOR							34
#define DISPID_PROGBAR_TEXTSHADOWOFFSETX						35
#define DISPID_PROGBAR_TEXTSHADOWOFFSETY						36
#define DISPID_PROGBAR_USESYSTEMFONT								37
#define DISPID_PROGBAR_DISPLAYPROGRESSINTASKBAR			38
#define DISPID_PROGBAR_HAPPLICATIONWINDOW						39
// fingerprint
#define DISPID_PROGBAR_APPID												500
#define DISPID_PROGBAR_APPNAME											501
#define DISPID_PROGBAR_APPSHORTNAME									502
#define DISPID_PROGBAR_BUILD												503
#define DISPID_PROGBAR_CHARSET											504
#define DISPID_PROGBAR_ISRELEASE										505
#define DISPID_PROGBAR_PROGRAMMER										506
#define DISPID_PROGBAR_TESTER												507
// methods
#define DISPID_PROGBAR_ABOUT												DISPID_ABOUTBOX
#define DISPID_PROGBAR_CHANGECURRENTVALUE						24
#define DISPID_PROGBAR_LOADSETTINGSFROMFILE					25
#define DISPID_PROGBAR_REFRESH											DISPID_REFRESH
#define DISPID_PROGBAR_SAVESETTINGSTOFILE						26
#define DISPID_PROGBAR_FINISHOLEDRAGDROP						40


// _IProgressBarEvents
// methods
#define DISPID_PROGBARE_CLICK												DISPID_VALUE
#define DISPID_PROGBARE_CONTEXTMENU									1
#define DISPID_PROGBARE_DBLCLICK										2
#define DISPID_PROGBARE_DESTROYEDCONTROLWINDOW			3
#define DISPID_PROGBARE_MCLICK											4
#define DISPID_PROGBARE_MDBLCLICK										5
#define DISPID_PROGBARE_MOUSEDOWN										6
#define DISPID_PROGBARE_MOUSEENTER									7
#define DISPID_PROGBARE_MOUSEHOVER									8
#define DISPID_PROGBARE_MOUSELEAVE									9
#define DISPID_PROGBARE_MOUSEMOVE										10
#define DISPID_PROGBARE_MOUSEUP											11
#define DISPID_PROGBARE_OLEDRAGDROP									12
#define DISPID_PROGBARE_OLEDRAGENTER								13
#define DISPID_PROGBARE_OLEDRAGLEAVE								14
#define DISPID_PROGBARE_OLEDRAGMOUSEMOVE						15
#define DISPID_PROGBARE_RCLICK											16
#define DISPID_PROGBARE_RDBLCLICK										17
#define DISPID_PROGBARE_RECREATEDCONTROLWINDOW			18
#define DISPID_PROGBARE_RESIZEDCONTROLWINDOW				19
#define DISPID_PROGBARE_XCLICK											20
#define DISPID_PROGBARE_XDBLCLICK										21


// IOLEDataObject
// properties
// methods
#define DISPID_ODO_CLEAR														1
#define DISPID_ODO_GETCANONICALFORMAT								2
#define DISPID_ODO_GETDATA													3
#define DISPID_ODO_GETFORMAT												4
#define DISPID_ODO_SETDATA													5
#define DISPID_ODO_GETDROPDESCRIPTION								6
#define DISPID_ODO_SETDROPDESCRIPTION								7
